/**
 * Golden tests: canonical games with HAND-VERIFIED expected results stored as JSON in ./golden.
 * Expected values were derived by hand (see each fixture's story), not generated by the engine.
 */
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  analyse,
  analyseExact,
  compareWithSimultaneous,
  type GameDefinition,
  type NormalGame,
  type Profile,
  type Sequential2Game,
  type RepeatedGame,
  validateGame,
} from '../src/index.js';

const dir = join(import.meta.dirname, 'golden');
const files = readdirSync(dir).filter((f) => f.endsWith('.json')).sort();

interface Fixture {
  name: string;
  story: string;
  handVerified: true;
  game: GameDefinition;
  expected: Record<string, unknown>;
}

const load = (f: string): Fixture => JSON.parse(readFileSync(join(dir, f), 'utf8')) as Fixture;

function ids(game: NormalGame | Sequential2Game) {
  const row = game.players[0]!.actions.map((a) => a.id);
  const col = game.players[1]!.actions.map((a) => a.id);
  return {
    row,
    col,
    prof: (p: readonly number[]) => [row[p[0]!]!, col[p[1]!]!],
    rows: (xs: readonly number[]) => xs.map((i) => row[i]!),
    cols: (xs: readonly number[]) => xs.map((j) => col[j]!),
  };
}

const sortJ = <T,>(xs: T[]) => xs.map((x) => JSON.stringify(x)).sort();

describe('golden fixtures', () => {
  it('fixture set is complete', () => {
    const names = files.map((f) => f.replace('.json', ''));
    for (const required of [
      'pd-roommates-kitchen',
      'stag-hunt-joint-project',
      'chicken-narrow-bridge',
      'battle-of-the-sexes-friends-evening',
      'pure-coordination-corridor',
      'matching-pennies-guess-the-hand',
      'harmony-shared-garden',
      'deadlock-neighbouring-stalls',
      'rock-paper-scissors',
      'iesds-2x3-studio-booking',
      'weak-dominance-order-seating',
      'degenerate-continuum-picnic-spot',
      'sequential-cafe-opens-near-rival',
    ]) {
      expect(names).toContain(required);
    }
  });

  for (const f of files) {
    const fx = load(f);
    describe(fx.name, () => {
      it('is a valid, hand-verified game definition', () => {
        expect(fx.handVerified).toBe(true);
        expect(validateGame(fx.game)).toMatchObject({ ok: true });
      });

      if (fx.game.kind === 'normal') {
        const g = fx.game;
        const e = fx.expected as Record<string, any>;
        const I = ids(g);
        const facts = analyse(g);
        const m = facts.matrix;

        it('pure Nash equilibria', () => {
          expect(sortJ(m.equilibria.pure.map(I.prof))).toEqual(sortJ(e.pureNE));
        });
        it('mixed (isolated) equilibria, exact', () => {
          expect(sortJ(m.equilibria.mixed)).toEqual(sortJ(e.mixedNE));
          expect(sortJ(m.equilibriumPayoffs.mixed)).toEqual(sortJ(e.mixedPayoffs));
        });
        it('continua and degeneracy', () => {
          const got = m.equilibria.continua.map((c) => ({ row: [...c.vertices[0]].map((v) => JSON.stringify(v)).sort(), col: [...c.vertices[1]].map((v) => JSON.stringify(v)).sort() }));
          const exp = (e.continua as { row: string[][]; col: string[][] }[]).map((c) => ({ row: c.row.map((v) => JSON.stringify(v)).sort(), col: c.col.map((v) => JSON.stringify(v)).sort() }));
          expect(sortJ(got)).toEqual(sortJ(exp));
          expect(m.equilibria.degenerate).toBe(e.degenerate);
          expect(m.equilibria.finite).toBe(e.finite);
          expect(m.equilibria.complete).toBe(true);
        });
        it('never reports an empty equilibrium set', () => {
          const n = m.equilibria.pure.length + m.equilibria.mixed.length + m.equilibria.continua.length;
          expect(n).toBeGreaterThan(0);
        });
        it('family classification', () => {
          expect(m.family.family).toBe(e.family);
          if (e.familyApplicable !== undefined) expect(m.family.applicable).toBe(e.familyApplicable);
          if (e.pdRepeatedCondition !== undefined) expect(m.family.pdRepeatedCondition?.holds).toBe(e.pdRepeatedCondition);
          if (e.subtype !== undefined) expect(m.family.subtype).toBe(e.subtype);
        });
        it('dominance and IESDS', () => {
          const sd = m.dominance.map((d, p) => (d.strictlyDominantAction === null ? null : (p === 0 ? I.row : I.col)[d.strictlyDominantAction]));
          expect({ row: sd[0], col: sd[1] }).toEqual(e.strictlyDominant);
          expect({ row: I.rows(m.iesds.surviving[0]), col: I.cols(m.iesds.surviving[1]) }).toEqual(e.iesdsSurviving);
          const steps = m.iesds.steps.map((s) => ({
            round: s.round,
            player: s.player,
            action: (s.player === 0 ? I.row : I.col)[s.action],
            dominatedBy: s.dominatedBy.map((a) => (s.player === 0 ? I.row : I.col)[a]),
          }));
          expect(steps).toEqual(e.iesdsSteps);
          expect(m.iesds.orderDependent).toBe(false);
        });
        if (e.iwdsOrderDependent !== undefined) {
          it('iterated weak dominance is flagged order-dependent with every possible result', () => {
            const w = m.iteratedWeakDominance;
            expect(w.orderDependent).toBe(e.iwdsOrderDependent);
            expect({ row: I.rows(w.surviving[0]), col: I.cols(w.surviving[1]) }).toEqual(e.iwdsSurviving);
            const got = w.possibleResults.map(([r, c]) => ({ row: I.rows(r), col: I.cols(c) }));
            expect(sortJ(got)).toEqual(sortJ(e.iwdsPossibleResults));
            expect(w.warning).toMatch(/order/);
          });
        }
        it('Pareto analysis', () => {
          expect(sortJ(m.pareto.efficient.map(I.prof))).toEqual(sortJ(e.paretoEfficient));
          expect(m.pareto.everyEquilibriumParetoDominated).toBe(e.everyEquilibriumParetoDominated);
        });
        it('facts are JSON round-trippable', () => {
          expect(JSON.parse(JSON.stringify(facts))).toEqual(facts);
        });
      }

      if (fx.game.kind === 'sequential2') {
        const g = fx.game;
        const e = fx.expected as Record<string, any>;
        const I = ids(g);
        const cmp = compareWithSimultaneous(g);
        const facts = analyse(g);
        it('follower best responses and SPE', () => {
          expect(facts.sequential!.followerBestResponses.map((b) => I.cols(b))).toEqual(e.followerBestResponses);
          expect(cmp.backwardInduction.spe).toHaveLength(e.speCount);
          expect(sortJ(cmp.backwardInduction.outcomes.map(I.prof))).toEqual(sortJ(e.speOutcomes));
          expect([...new Set(cmp.speLeaderPayoffs.map(String))]).toEqual(e.speLeaderPayoffs);
          expect(cmp.backwardInduction.onPathTie).toBe(e.onPathTie);
          expect(
            cmp.backwardInduction.followerTies.map((t) => ({ leaderAction: I.row[t.leaderAction], responses: I.cols(t.responses) })),
          ).toEqual(e.followerTies);
        });
        it('simultaneous version: NE set differs from SPE', () => {
          expect(sortJ(cmp.simultaneous.pure.map(I.prof))).toEqual(sortJ(e.simultaneousPureNE));
          expect(cmp.simultaneous.mixed).toHaveLength(e.simultaneousMixedNE.length);
          const cont = facts.matrix.equilibria.continua.map((c) => ({ row: [...c.vertices[0]].map((v) => JSON.stringify(v)).sort(), col: [...c.vertices[1]].map((v) => JSON.stringify(v)).sort() }));
          const exp = (e.simultaneousContinua as { row: string[][]; col: string[][] }[]).map((c) => ({ row: c.row.map((v) => JSON.stringify(v)).sort(), col: c.col.map((v) => JSON.stringify(v)).sort() }));
          expect(sortJ(cont)).toEqual(sortJ(exp));
          expect(sortJ(cmp.simultaneousPureNENotSPEOutcome.map((p: Profile) => I.prof(p)))).toEqual(sortJ(e.simultaneousNotSPE));
          expect(cmp.firstMover).toBe(e.firstMover);
        });
      }

      if (fx.game.kind === 'repeated') {
        const g = fx.game as RepeatedGame;
        const e = fx.expected as Record<string, any>;
        const facts = analyseExact(g);
        it('grim threshold and finite-horizon unravelling', () => {
          const rep = facts.repeated!;
          expect(rep.grimThreshold.deltaStar!.toString()).toBe(e.deltaStar);
          expect(rep.grimThreshold.perPlayer!.map(String)).toEqual(e.perPlayer);
          if (e.sustainable === null) expect(rep.grimAtDelta).toBeNull();
          else {
            expect(rep.grimAtDelta!.sustainable).toBe(e.sustainable);
            expect(rep.grimAtDelta!.cooperateValue!.map(String)).toEqual(e.cooperateValue);
            expect(rep.grimAtDelta!.deviateValue!.map(String)).toEqual(e.deviateValue);
          }
          expect(rep.finiteHorizon.applies).toBe(e.finiteHorizonApplies);
          if (e.stageEquilibrium) {
            expect(rep.finiteHorizon.stageEquilibrium!.map((v) => v.map(String))).toEqual(e.stageEquilibrium);
            expect(rep.finiteHorizon.steps.map((s) => s.round)).toEqual(e.unravelRounds);
          }
        });
      }
    });
  }
});
